### ISSUE TITLE
/health API returns 503 when /sdks API returns 200

### ISSUE THREAD

**Issue by bqbn** [getsentry/symbolserver#3]
We're trying to set up an on-premise symbol server using v1.10.0. The server can start up, however, the /health API always returns 503.

The program runs like this:

```
# ./sentry-symbolserver-Linux-x86_64 --config /etc/sentry/config.yml run
[2018-02-15 08:09:26.967366614 +00:00] libsymbolserver | Checking for symbols from S3 in background every 2 minutes
[2018-02-15 08:09:26.967455177 +00:00] libsymbolserver | Source Bucket: s3://sentrysymbolservers3buck-rc28fxzhcjag/
[2018-02-15 08:09:26.967504413 +00:00] libsymbolserver | Local SDKs: 0
[2018-02-15 08:09:26.967926966 +00:00] libsymbolserver | Running healthcheck every 1 minute
[2018-02-15 08:09:27.136512458 +00:00] libsymbolserver | Listening on http://127.0.0.1:9000/
[2018-02-15 08:09:27.136532473 +00:00] libsymbolserver | Spawning 2 listener threads
```

Here is when curling the /health API.
```
# curl -i localhost:9000/health
HTTP/1.1 503 Service Unavailable
Server: sentry-symbolserver/1.10.0
Content-Length: 53
Content-Type: application/json
Date: Thu, 15 Feb 2018 08:09:42 GMT

{"is_offline":false,"is_healthy":false,"sync_lag":0}
```
Meanwhile, if we curl the /sdks API, it returns 200.

```
# curl -i localhost:9000/sdks
HTTP/1.1 200 OK
Server: sentry-symbolserver/1.10.0
Content-Length: 12
Content-Type: application/json
Date: Thu, 15 Feb 2018 08:36:45 GMT

{"sdks":[]}
```

We tried to set the logging level to be `trace`, but the program still doesn't output errors when it's returning 503 for /health API. We're not sure what/where the problem is, or how to further troubleshoot it.

Our config.yml looks like this for reference purpose.

```
# cat /etc/sentry/config.yml
aws:
  access_key: xxx
  secret_key: xxx
  bucket_url: s3://sentrysymbolservers3buck-rc28fxzhcjag/
  region: us-east-1

symbol_dir: /data/symbol_server

server:
  host: '127.0.0.1'
  port: 9000
  healthcheck_interval: 60

sync:
  interval: 120
  ignore:
#    - '*'
    - '!iOS_10.*'
    - '!iOS_9.*'

log:
  level: trace
  file: null
```

**Comment by mitsuhiko** [comment]
Sounds like your S3 bucket is empty? /sdks always returns 200.

**Comment by bqbn** [comment]
Yeah, this is a new set up and the S3 bucket is empty at the moment.

It feels a little odd `/health` returns 503 when S3 bucket is empty though. I can understand `/health` returns 503 if the symbolserver has trouble connecting to the S3 bucket (due to networking or permission errors for example), but maybe an empty bucket should be a normal case.

We'd like to put the symbolserver behind an ELB, however we can't use `/health` as the health check endpoint for the ELB due to the above, because we don't know when the s3 bucket will be empty.

Since you say `/sdks` always returns 200, it's tempting to use `/sdks` as the health check endpoint for the ELB, only it isn't called `/health`. 

Is it possible to make empty S3 bucket a valid case for the `/health` endpoint?

**Comment by mitsuhiko** [comment]
I'm not sure why the S3 bucket would ever be empty. We intentionally do not permit an empty S3 bucket in the healthcheck because this means a misconfiguration on the users side.

Maybe there is a misunderstanding of what the symbolserver does that you are pointing it to an empty S3 bucket?

**Comment by bqbn** [comment]
Our team doesn't use the on-premise Sentry service (including the symbol server), we only help set up and maintain the infrastructure. The developers from different teams within our organization use the Sentry service and they upload symbol files to the s3 bucket. They haven't done that yet, thus the s3 bucket is empty. 

However, from our team's perspective, there is nothing wrong with an empty s3 bucket since our users will upload those files eventually. That's why I was asking if it's possible to make an empty s3 bucket a valid case for the health check.

I know some other organizations have separate dev and infrastructure teams too, so I don't know if our use case is uncommon or not.

**Comment by mitsuhiko** [comment]
@bqbn the situation is that the symbol server is exclusively used for iOS system symbols not for application symbols. In the case of sentry.io we have a dedicated team which ingests the system symbols.

The symbols the actual development teams need to be concerned with do not use the symbolserver.

> That's why I was asking if it's possible to make an empty s3 bucket a valid case for the health check.

This would be a concern for sentry.io as we consider an empty s3 bucket to be an unhealthy symbol server that should be taken out of rotation.

**Comment by mitsuhiko** [comment]
I'm going to close this issue for now as I do not believe we're going to change this behavior.
